version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Use the environment variable
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Use the environment variable
      POSTGRES_DB: ${POSTGRES_DB}  # Use the environment variable
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data in a volume

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}  # Use the environment variable
    depends_on:
      - db

volumes:
  db_data:  # This defines the volume for persistent storage
